In [1]:
import numpy as np
x = np.array([3, 4])
print("sqrt(dot(x, x)) = ", np.sqrt(np.dot(x, x)))
print("sqrt(sum(x, x)) = ", np.sqrt(np.sum(x * x))) # 
print("norm(x) = " , np.linalg.norm(x))

sqrt(dot(x, x)) =  5.0
sqrt(sum(x, x)) =  5.0
norm(x) =  5.0


In [2]:
x = np.array([3, 4, 5, 6])
print("norm(x) = ", np.linalg.norm(x))

norm(x) =  9.273618495495704


In [3]:
v = np.array([3, 4])
u = v / np.linalg.norm(v)
print(u)
print(np.linalg.norm(u))

[0.6 0.8]
1.0


In [4]:
v = np.array([3, 4, 5, 6])
u = v / np.linalg.norm(v)
print(u)

[0.32349832 0.43133109 0.53916387 0.64699664]


In [5]:
a = np.array([8, 13])
b = np.array([26, 7])
c = a + b
print(c)

[34 20]


In [6]:
d = np.array([4, 5])
e = np.array([3, 8])
f = d + e
print(f)

[ 7 13]


In [7]:
hero = np.array([0, 1])
enemyA = np.array([4, 3])
enemyB = np.array([4, -3])
hero_norm = np.linalg.norm(hero)
enemyA_norm = np.linalg.norm(enemyA)
enemyB_norm = np.linalg.norm(enemyB)
h_eA_cos = np.dot(hero, enemyA) / (hero_norm * enemyA_norm)
h_eB_cos = np.dot(hero, enemyB) / (hero_norm * enemyB_norm)
print(h_eA_cos)
print(h_eB_cos)

0.6
-0.6


In [8]:
y = np.array([2, 4])
x = np.array([4, 3])
x_n = x / np.linalg.norm(x)
proj_result = np.dot(y, x_n) * x_n
print(proj_result)

[3.2 2.4]


In [9]:
y = np.array([3, 4])
x = np.array([1, 0])
x_n = x / np.linalg.norm(x)
proj_result = np.dot(y, x_n) * x_n
print(proj_result)

[3. 0.]


In [10]:
y = np.array([3, 4])
x = np.array([0, 1])
x_n = x / np.linalg.norm(x)
proj_result = np.dot(y, x_n) * x_n
print(proj_result)

[0. 4.]


In [11]:
A = np.array([[1,2], [3,4]])
A_inv = np.linalg.inv(A)
np.set_printoptions(formatter={'float' : '{: 0.3f}'.format})
print("A = \n", A)
print("Inverse of A = \n", A_inv)
print("A * A_inv = \n", np.dot(A, A_inv))
print("A_inv * A = \n", np.dot(A_inv, A))

A = 
 [[1 2]
 [3 4]]
Inverse of A = 
 [[-2.000  1.000]
 [ 1.500 -0.500]]
A * A_inv = 
 [[ 1.000  0.000]
 [ 0.000  1.000]]
A_inv * A = 
 [[ 1.000  0.000]
 [ 0.000  1.000]]


In [12]:
A = np.array([[1,2,3], [6,5,4], [9,8,7]])
W, V = np.linalg.eig(A)
print(W)
print(V)

[ 14.639 -1.639 -0.000]
[[ 0.255  0.789  0.408]
 [ 0.502 -0.493 -0.816]
 [ 0.826 -0.366  0.408]]


In [14]:
W, V = np.linalg.eig(np.transpose(A)) # 전치하여도 변하지 않는다
print(W)
print(V)

[ 14.639 -1.639  0.000]
[[ 0.611  0.880 -0.239]
 [ 0.577  0.233 -0.796]
 [ 0.542 -0.414  0.557]]


In [15]:
B = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]]) # 삼각행렬의 고윳값은 대각행렬의 성분들과 일치한다
W, V = np.linalg.eig(B)
print(W)
print(V)

[ 1.000  2.000  3.000]
[[ 1.000  0.000  0.000]
 [ 0.000  1.000  0.000]
 [ 0.000  0.000  1.000]]


In [16]:
W, V = np.linalg.eig(np.linalg.inv(B)) # 
print(W)
print(V)

[ 1.000  0.500  0.333]
[[ 1.000  0.000  0.000]
 [ 0.000  1.000  0.000]
 [ 0.000  0.000  1.000]]
