## 공분산

In [5]:
import numpy as np
x_1 = np.array([3,4,5,4,3,4,5])
x_2 = np.array([1,2,3,4,5,6,7])
x_3 = np.array([4,4,4,4,4,4,4])

x1_diff = x_1 - x_1.mean()
x2_diff = x_2 - x_2.mean()
x12_cov = np.dot(x1_diff, x2_diff) / 6
print("covariance of x_1 and x_2 is : ", x12_cov)
print("correlation coefficient of x_1 and x_2 is : ", x12_cov / (x_1.std() * x_2.std()))

covariance of x_1 and x_2 is :  0.6666666666666666
correlation coefficient of x_1 and x_2 is :  0.44095855184409843


In [8]:
x = np.arange(5)
y = np.arange(4, -1, -1)
x_diff = x - x.mean()
y_diff = y - y.mean()
xy_cov = np.dot(x_diff, y_diff) / 5
print("covariance of x and y is : ", xy_cov)
print("covariance matrix of x and y is : \n", np.cov(x, y, ddof=0))
print("correlation coefficient of x and y is : \n", np.corrcoef(x, y)) # 오른쪽에서 내려오는 대각을 본다. 완벽한 음의 상관관계

covariance of x and y is :  -2.0
covariance matrix of x and y is : 
 [[ 2. -2.]
 [-2.  2.]]
correlation coefficient of x and y is : 
 [[ 1. -1.]
 [-1.  1.]]


In [11]:
x_1 = np.array([35, 5, 0, 20, 15])
x_2 = np.array([11,12, 5, 9, 8])
x_3 = np.array([0.5, 0, 10, 4.5, 5])
x_1_mean = x_1.mean()
x_2_mean = x_2.mean()
x_3_mean = x_3.mean()
print("mean: " , x_1_mean, x_2_mean, x_3_mean)

x_1_var = x_1.var()
x_2_var = x_2.var()
x_3_var = x_3.var()

print("var: " , x_1_var, x_2_var, x_3_var)
x_total = np.array([x_1, x_2, x_3])

print(x_total)

print('Covariance matrix : \n', np.cov(x_total, ddof=0))
X_cc = np.corrcoef(x_total)

print('Correlation Coefficients : \n', X_cc)

print(f'rcho(x1, x2) : {X_cc[1][0]:3.2}')
print(f'rcho(x2, x3) : {X_cc[1][2]:3.2}')
print(f'rcho(x3, x1) : {X_cc[2][0]:3.2}')


mean:  15.0 9.0 4.0
var:  150.0 6.0 13.1
[[35.   5.   0.  20.  15. ]
 [11.  12.   5.   9.   8. ]
 [ 0.5  0.  10.   4.5  5. ]]
Covariance matrix : 
 [[150.   14.  -23.5]
 [ 14.    6.   -8.8]
 [-23.5  -8.8  13.1]]
Correlation Coefficients : 
 [[ 1.          0.46666667 -0.53013513]
 [ 0.46666667  1.         -0.99259344]
 [-0.53013513 -0.99259344  1.        ]]
rcho(x1, x2) : 0.47
rcho(x2, x3) : -0.99
rcho(x3, x1) : -0.53


## 왜도, 첨도

In [12]:
import scipy.stats as ss

x1 = ss.skew([1,2,3,4,5,5,5,5]) #왼쪽으로 치우칠 수록 양수가 나온다
x2 = ss.skew([1,2,3,4,5,1,1,1]) #왜도를 0에 가깝게 만들어야 데이터 분석에 사용할 수 있다.
y1 = ss.kurtosis([1,2,2,2,3,3,3,3,3,4,4,4,5])
y2 = ss.kurtosis([1,2,3,4,5])
print(x1)
print(x2)
print(y1)
print(y2)

-0.7244179326244428
0.7244179326244428
-0.4795918367346941
-1.3


## 회귀분석
 - 표본으로부터 모집단의 분포를 추정

 - 통계적 현상 현상을 반복하여 관찰하거나 집단 안에서 대량으로 관찰하여 고유의 법칙성을 찾아내는 것이 가능한 현상
 - 확률: 통계적 현상의 확실함의 정도를 나타내는 척도